### PR TITLE
Faster Mat4 * Mat4 with SSE (at least on my machines)

### PR DESCRIPTION
**Pull request by Evrey**
This implementation is basically the old loop, but hand-unrolled for better ordering of intrinsics. Also mutates most no longer needed state to give LLVM an easier time with register selection. LLVM will re-order some things, as this code hits the 16 SIMD registers limit.

On my machines, this code consistently beats both, `nalgebra-glm` and the old loop version. Verify that before blindly merging. =)

Oh, and this also changes the benchmark code to use two non-trivial matrices.

### CODE REVIEW

**Comment by Lokathor** [comment]
Well you requested that I run the benchmarks on my own machine before I blindly merge it in.

Fair enough.

```
D:\dev\hektor>cargo bench
   Compiling hektor v0.0.2 (D:\dev\hektor)
    Finished release [optimized] target(s) in 1.14s
     Running target\release\deps\hektor-859f9488393123ed.exe

running 5 tests
test test_if_sse2_macro ... ignored
test test_if_sse3_macro ... ignored
test test_if_sse41_macro ... ignored
test test_if_sse42_macro ... ignored
test test_if_ssse3_macro ... ignored

test result: ok. 0 passed; 0 failed; 5 ignored; 0 measured; 0 filtered out

     Running target\release\deps\bench-0f9096f5320361fa.exe

running 2 tests
test bench_glm_identity_mat4_mult_mat4    ... bench:          10 ns/iter (+/- 4)
test bench_hektor_identity_mat4_mult_mat4 ... bench:          37 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out
```

D:

"What in the name of Ferris went wrong!?"

Then I kinda remembered that you'd mentioned LTO at one point, and that the default profiles for cargo/rust are actually really conservative about that stuff, so I added the following to the `Cargo.toml`
```toml
[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
```

Now the benchmarks go like this:

```
D:\dev\hektor>cargo bench
    Finished release [optimized] target(s) in 0.10s
     Running target\release\deps\hektor-8acae79ad80cc291.exe

running 5 tests
test test_if_sse2_macro ... ignored
test test_if_sse3_macro ... ignored
test test_if_sse41_macro ... ignored
test test_if_sse42_macro ... ignored
test test_if_ssse3_macro ... ignored

test result: ok. 0 passed; 0 failed; 5 ignored; 0 measured; 0 filtered out

     Running target\release\deps\bench-c1d7ef249d7689e3.exe

running 2 tests
test bench_glm_identity_mat4_mult_mat4    ... bench:           3 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           4 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out
```

I did several runs. Always 3ns for nalgebra-glm and 4ns for hektor, plu-mi-zero.

(CPU is an i7-8700)

**Comment by Evrey** [comment]
Using the LTO flags on my laptop:
```
test bench_glm_identity_mat4_mult_mat4    ... bench:          10 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           5 ns/iter (+/- 0)
```
Intel i5-8250U
rustc 1.33.0-nightly

Using the LTO flags on my desktop:
```
test bench_glm_identity_mat4_mult_mat4    ... bench:          11 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           5 ns/iter (+/- 0)
```
Intel i7-5820K
rustc 1.34.0-nightly

Without AVX enabled, `hektor` stay at 5ns, whereas `glm` gets worse by +2ns, for both of my CPUs.

Well, that's certainly interesting. Throw more science at it?

**Comment by xd009642** [comment]
Using the Cargo.toml mods @Evrey put above and running `cargo bench`

```
test bench_glm_identity_mat4_mult_mat4    ... bench:           4 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           4 ns/iter (+/- 0)
```

Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
rustc 1.34.0-nightly (8a57831a4 2019-02-02)

**Comment by Lokathor** [comment]
Let's note that the repo contains a cargo config file

```toml
[build]
rustflags = ["-C","target-feature=+crt-static","-C","target-cpu=native"]
```

If I _disable_ this file I get

```
running 2 tests
test bench_glm_identity_mat4_mult_mat4    ... bench:           4 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           4 ns/iter (+/- 0)
```

and when I have it _enabled_ I get the results first reported for my machine

```
running 2 tests
test bench_glm_identity_mat4_mult_mat4    ... bench:           3 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           4 ns/iter (+/- 0)
```

So... somehow I've got some super new feature that LLVM picks up on and then coverts nalgebra along a code path that's better for them and they manage to shave another nanosecond off?

**Comment by xd009642** [comment]
I just disabled the config file and got:

```
test bench_glm_identity_mat4_mult_mat4    ... bench:           5 ns/iter (+/- 0)
test bench_hektor_identity_mat4_mult_mat4 ... bench:           5 ns/iter (+/- 0)
```

I find it strange that on my pc they're always the same. Might be worth setting up a criterion benchmark to get some more information

**Pull request merged**
